#!/usr/bin/env python3
"""
Generate blocklist in various formats from meta_domains.txt.
Supports: hosts file, dnsmasq, Pi-hole, UniFi Dream Router instructions.
"""

import argparse
import sys
from pathlib import Path

DOMAIN_FILE = Path(__file__).parent / "meta_domains.txt"


def load_domains(path: Path = DOMAIN_FILE) -> list[str]:
    """Load domains from blocklist file, ignoring comments and blanks."""
    domains = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Remove inline comments
        if "#" in line:
            line = line.split("#")[0].strip()
        if line:
            domains.append(line)
    return domains


def format_hosts(domains: list[str]) -> str:
    """Generate /etc/hosts format (0.0.0.0 entries)."""
    lines = [
        "# Meta/Facebook Telemetry Blocklist",
        "# Generated by metarayban/blocklist/generate.py",
        "",
    ]
    for d in domains:
        lines.append(f"0.0.0.0 {d}")
    return "\n".join(lines) + "\n"


def format_dnsmasq(domains: list[str]) -> str:
    """Generate dnsmasq config format."""
    lines = [
        "# Meta/Facebook Telemetry Blocklist for dnsmasq",
        "# Place in /etc/dnsmasq.d/meta-block.conf",
        "",
    ]
    for d in domains:
        lines.append(f"address=/{d}/0.0.0.0")
    return "\n".join(lines) + "\n"


def format_pihole(domains: list[str]) -> str:
    """Generate Pi-hole compatible blocklist (one domain per line)."""
    lines = [
        "# Meta/Facebook Telemetry Blocklist for Pi-hole",
        "# Import via: Settings > Blocklists > Add",
        "",
    ]
    for d in domains:
        lines.append(d)
    return "\n".join(lines) + "\n"


def format_udr(domains: list[str]) -> str:
    """Generate instructions for UniFi Dream Router."""
    domain_list = "\n".join(f"  - {d}" for d in domains)
    return f"""# UniFi Dream Router (UDR) - Meta Telemetry Blocking
# =====================================================
#
# Option 1: Content Filtering (UniFi Network 8.x+)
# -------------------------------------------------
# 1. Open UniFi Network console (https://192.168.10.1)
# 2. Settings > Security > Content Filtering
# 3. Enable content filtering for the VLAN/network your phone is on
# 4. Add a custom blocklist with the domains below
#
# Option 2: Traffic Rules (Firewall)
# -----------------------------------
# 1. Settings > Security > Traffic & Firewall Rules
# 2. Create rule: Block traffic to these domains
# 3. Apply to the network/VLAN where your phone connects
#
# Option 3: Custom DNS (if running local DNS)
# ---------------------------------------------
# Point your UDR to a Pi-hole or AdGuard Home instance
# and import meta_domains.txt as a blocklist
#
# Domains to block:
{domain_list}

# Pro tip: Create a separate VLAN/SSID for your phone when using
# the Meta View app. Apply blocking rules only to that network.
# This way, you can toggle blocking on/off by switching WiFi networks.
"""


def main():
    parser = argparse.ArgumentParser(
        description="Generate Meta telemetry blocklist in various formats"
    )
    parser.add_argument(
        "--format", "-f",
        choices=["hosts", "dnsmasq", "pihole", "udr"],
        default="hosts",
        help="Output format (default: hosts)"
    )
    parser.add_argument(
        "--output", "-o",
        help="Output file (default: stdout)"
    )
    parser.add_argument(
        "--domains", "-d",
        default=str(DOMAIN_FILE),
        help="Path to domain list file"
    )
    args = parser.parse_args()

    domains = load_domains(Path(args.domains))
    print(f"Loaded {len(domains)} domains", file=sys.stderr)

    formatters = {
        "hosts": format_hosts,
        "dnsmasq": format_dnsmasq,
        "pihole": format_pihole,
        "udr": format_udr,
    }

    output = formatters[args.format](domains)

    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
